In [2]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.optim as optim
from torch.utils.data import DataLoader
from Common import NeuralNet
import time

torch.autograd.set_detect_anomaly(True)
torch.manual_seed(128)

In [45]:
a = torch.tensor([[1,2],[3,4],[5,6],[1,7],[3,8],[5,9],[1,10],[3,11],[5,12]])
print(a)
print(a.shape)

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 1,  7],
        [ 3,  8],
        [ 5,  9],
        [ 1, 10],
        [ 3, 11],
        [ 5, 12]])
torch.Size([9, 2])


In [46]:
print(a.shape[0]/3)

3.0


In [51]:
for j in range(3):
    for i in range(int(a.shape[0]/3)):
        print(a[3*j+i,:])
    print('ciao')

tensor([1, 2])
tensor([3, 4])
tensor([5, 6])
ciao
tensor([1, 7])
tensor([3, 8])
tensor([5, 9])
ciao
tensor([ 1, 10])
tensor([ 3, 11])
tensor([ 5, 12])
ciao


In [54]:
a

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 1,  7],
        [ 3,  8],
        [ 5,  9],
        [ 1, 10],
        [ 3, 11],
        [ 5, 12]])

In [56]:
a[:int(a.shape[0]/3),:]

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [58]:
a[int(a.shape[0]/3):int(2*a.shape[0]/3),:]

tensor([[1, 7],
        [3, 8],
        [5, 9]])